from __future__ import annotations

from decimal import Decimal
from typing import List, Optional, Protocol, runtime_checkable

from app.domain.entities import Account, Customer, LedgerEntry, Transaction
from app.domain.value_objects import AccountId, CustomerId


@runtime_checkable
class CustomerRepository(Protocol):
    def save(self, customer: Customer) -> Customer: ...
    def find_by_id(self, customer_id: CustomerId) -> Optional[Customer]: ...
    def find_by_email(self, email: str) -> Optional[Customer]: ...
    def list_all(self) -> List[Customer]: ...


@runtime_checkable
class AccountRepository(Protocol):
    def save(self, account: Account) -> Account: ...
    def find_by_id(self, account_id: AccountId) -> Optional[Account]: ...
    def find_by_customer_id(self, customer_id: CustomerId) -> List[Account]: ...
    def update_balance(self, account: Account) -> None: ...


@runtime_checkable
class TransactionRepository(Protocol):
    def save(self, transaction: Transaction) -> Transaction: ...
    def find_by_id(self, transaction_id: str) -> Optional[Transaction]: ...
    def find_by_account_id(
        self, account_id: AccountId, limit: int = 50, offset: int = 0
    ) -> List[Transaction]: ...
    def count_recent_by_account(self, account_id: AccountId, minutes: int) -> int: ...
    def sum_today_by_account(self, account_id: AccountId) -> Decimal: ...


@runtime_checkable
class LedgerRepository(Protocol):
    def save(self, entry: LedgerEntry) -> LedgerEntry: ...
    def find_by_account_id(self, account_id: AccountId) -> List[LedgerEntry]: ...
    def find_by_transaction_id(self, transaction_id: str) -> List[LedgerEntry]: ...